
/**
 * @file sudoku.cpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author Cheikh ABK
 * @date 2000-11-14                                                                     
 **/
 
#include <iostream>
#include "sudokuCode.hpp"

using namespace std;
using namespace SmartBlocks;

int main(int argc, char **argv) {
    try {
        createSimulator(argc, argv, SudokuCode::buildNewBlockCode);
        getSimulator()->printInfo();
        BaseSimulator::getWorld()->printInfo();
        deleteSimulator();
    } catch(std::exception const& e) {
        cerr << "Uncaught exception: " << e.what();
    }

    return 0;
}